### ISSUE TITLE
Definition von Idle Time 

### ISSUE THREAD

**Issue by ckrey** [simra-project/simra-ios#1]
- was ist die Definition von idle? Gesamtlänge der 3-Sekunden-Abschnitte in denen die Geschwindigkeit 0 km/h ist? Oder Gesamtlänge der 3-Sekunden-Abschnitte
in denen sich die Position von Punkt zu Punkt um weniger als x Meter ändert?
 
Hier bin ich mir noch nicht sicher (ist auch noch nicht implementiert). Wenn die Distanz zum letzten 3-Sekunden-Abschnitt 0 Meter beträgt, erhöht sich die Dauer von idle um 3 Sekunden. Das könnte eine recht einfache Metrik sein.

**Comment by selphiron** [comment]
Ein 3-Sekunden Abschnitt, dessen Geschwindigkeit unter 3 km/h ist, wird als idle eingestuft, das heißt die idle Zeit (dieser Fahrt) wird um 3 Sekunden erhöht.
