### ISSUE TITLE
Show count of "scary" events in statistics

### ISSUE THREAD

**Issue by ckrey** [simra-project/simra-ios#19]
Es ist geplant in der Statistik auch zu zeigen, wie viele der Ereignisse beängstigend/scary waren.

**Comment by ckrey** [comment]
@selphiron  Nur lokal in der Anzeige, oder auch im immer wieder hochgeladenen Profil?

> birth,gender,region,experience,numberOfRides,duration,numberOfIncidents,length,idle

**Comment by selphiron** [comment]
Auch im Hochgeladenen Profil.
birth,gender,region,experience,numberOfRides,duration,numberOfIncidents,length,idle,numberOfScary
