### ISSUE TITLE
Upload status message for rides is not readable

### ISSUE THREAD

**Issue by MoeweX** [simra-project/simra-ios#20]
Every time a ride is uploaded, the app uploads the profile as well (which is fine).
The status code of the profile upload, however, hides the status code of the ride upload.

Maybe adding both to the same pop up could be an option?

**Comment by ckrey** [comment]
If the status of the ride uploads is not ok (<> HTTP 2xx), the profile is not uploaded and the error message is displayed.

So, if you see the profile status, you can assume the ride upload did succeed

**Comment by MoeweX** [comment]
Thanks for the fast response! I know that everything was successful when I get the profile 2xx message, but I still think it is counter intuitive to receive a profile success when uploading a ride, especially if the user is not familiar with the internals.

Still, I consider this very low priority ;). So maybe a good first task if someone else wants to start contributing to the SimRa IOS version :).

**Comment by ckrey** [comment]
<img width="375" alt="Screenshot 2020-01-21 at 13 12 57" src="https://user-images.githubusercontent.com/4027289/72804012-c2698680-3c4f-11ea-80bb-3374912c6136.png">

**Comment by ckrey** [comment]
done in #45
