### ISSUE TITLE
Repeated crashes/app freezes after unlocking the screen during a ride

### ISSUE THREAD

**Issue by cstuder** [simra-project/simra-ios#21]
Multiple times I had the app freeze or crash on me.

(iPhone 6, iOS 12.4.1)

_Scenario_

1. Start the app, start tracking.
1. Locking the phone.
1. Ride
1. Stop, unlock the phone.

The app is unresponsive, showing the correct position, but not reacting to button presses.

Most time it's frozen and needs to be killed in the multistasking screen. The ride is not saved in that case.

Recently it crashed on me at that moment, I've attached the crash log to the issue.

[SimRa-2019-09-10-122458.ips.txt](https://github.com/simra-project/simra-ios/files/3600966/SimRa-2019-09-10-122458.ips.txt)

**Comment by ckrey** [comment]
This might be related to low available memory or the calculation necessary when terminating a ride took too long: 
```
Exception Type:  EXC_CRASH (SIGKILL)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: Namespace SPRINGBOARD, Code 0x8badf00d
Termination Description: SPRINGBOARD, scene-update watchdog transgression: de.tu-berlin.mcc.simra exhausted real (wall clock) time allowance of 10.00 seconds | ProcessVisibility: Foreground | ProcessState: Running | WatchdogEvent: scene-update | WatchdogVisibility: Foreground | WatchdogCPUStatistics: ( | "Elapsed total CPU time (seconds): 8.190 (user 8.190, system 0.000), 41% CPU", | "Elapsed application CPU time (seconds): 0.007, 0% CPU" | )
Triggered by Thread:  0
```

We will try to add some debug code or a temptative fix in the next version

**Comment by cstuder** [comment]
BTW: Haven't seen any crashes in a while.

**Comment by ckrey** [comment]
closing b/c no new reports or details
