### ISSUE TITLE
Additional statistics

### ISSUE THREAD

**Issue by selphiron** [simra-project/simra-ios#23]
Three additional metrics in statistics:
Average Speed: The average speed of all rides (without idle).
CO2 savings: How much CO2 was saved by the user for riding a bicycle over driving a car. Each km saves 138g CO2.
Scary incidents: Number of scary incidents.

**Comment by ckrey** [comment]
- Average Speed:
How to calculate "The average speed of all rides (without idle)." ?
Will this information be transmitted to the backend? New layout of the uploaded file?

- CO2 savings:
I assume this will be calculated on the fly based on the total length of the rides recorded so far and
will not be transmitted to the backend. Correct?

- Scary Incidents: 
Number of scary incidents was already implemented in the last version

**Comment by selphiron** [comment]
Average Speed = distance / (ride time - idle time)

Since the statistics contain only information about uploaded rides, I included them in the profile data, which is being uploaded to the backend after each ride upload. The header looks like this:
`birth,gender,region,experience,numberOfRides,duration,numberOfIncidents,waitedTime,distance,co2,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,behaviour,numberOfScary`

**Comment by ckrey** [comment]
mmh, currently the header looks like this
```
birth,gender,region,experience,numberOfRides,duration,numberOfIncidents,length,idle,numberOfScary,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23
```

Does this mean 
- `waitedTime/idle` and `distance/length` changed position,
- `co2` is inserted before the hours and why is is transmitted at all (see above)
- `behaviour` is new and unknown to me
- `numberOfScary` is behind the hours

**Comment by ckrey** [comment]
![IMG_8588](https://user-images.githubusercontent.com/4027289/65251804-4243e080-daf8-11e9-8025-8422a1eda8e2.png)

**Comment by selphiron** [comment]
behaviour is a new value in "Profile", where the user can say how much s/he adheres to the rules. I implemented it as a slider with the value 0 (most left) being "never" and 5 (most right) being "always". The slider is optional and can be toggled on and off by the user.
Suggestion: "Davon beängstigend" instead of  "Beängstigende Ereignisse". You are right about co2. And I think a different header for iOS and Android version isn't a problem.
