### ISSUE TITLE
Downloadable Regions

### ISSUE THREAD

**Issue by ckrey** [simra-project/simra-ios#25]
separated from #22

- Yes, that would be a good idea. But the last downloaded table should be saved locally, in case the user does not have a working internet connection, when the app starts. I will inform you, when the backend is ready for this.

- That would propably a good idea. Maybe ditch the numers altogether and write the region name instead? In that case the table from the backend would just contain a list with display name (eng)=display name(ger)=api-loc name\n(break line). As of now, it would look like this:

```
Please Choose=Bitte auswählen=UNKNOWN,
Berlin/Potsdam=Berlin/Potsdam=Berlin,
Other=Sonstiges=other,
Bern=Bern=Bern,
Pforzheim/Enzkreis=Pforzheim/Enzkreis=Pforzheim,
Augsburg=Augsburg=Augsburg
Bochum=Bochum=Bochum
```

- I think it would be a good idea to sort the entries alphabetically, when receiving the table. What do you think?

**Comment by selphiron** [comment]
So this approach it is?

**Comment by ckrey** [comment]
Yes, approach is fine. As long as the payload is relatively small (small number of regions), we do not have to implement a `if-modified-since` / `expires` mechanism.

Yes, a local cache will be used in off-line situations.

**Comment by selphiron** [comment]
You can GET the region list via /check/regions?clientHash=<HASH>
When a line starts with an "!", it means that the region is not supported for now and thus, should not be selectable (nor shown).
Each line ends with a line break (CR, LF) and not with a comma.
The actual list looks like this:
Please Choose=Bitte auswählen=UNKNOWN
!London=London=London
Berlin/Potsdam=Berlin/Potsdam=Berlin
Other=Sonstiges=other
Bern=Bern=Bern
Pforzheim/Enzkreis=Pforzheim/Enzkreis=Pforzheim
Augsburg=Augsburg=Augsburg
Ruhr region=Ruhrgebiet=Ruhrgebiet

**Comment by ckrey** [comment]
@selphiron I will do the changes in the next 2 weeks

**Comment by ckrey** [comment]
@selphiron 
I assume we replace the region id used in the `trips.csv` with region identifier e.g. ("Berlin" instead of 1)

**Comment by ckrey** [comment]
Where have `Bochum` and `Stuttgart` gone?
