### ISSUE TITLE
Mountain Bike as bike type

### ISSUE THREAD

**Issue by selphiron** [simra-project/simra-ios#26]
The option for a mountain bike is missing. The "wrong" bicycle names don't have to be renamed. Adding mountain bike should do.

These are the bike types:
              0 = not chosen
              1 = City-/Trekking Bike
              2 = Road Racing Bike
              3 = E-Bike
              4 = Recumbent Bicycle
              5 = Freight Bicycle
              6 = Tandem Bicycle
              7 = Mountainbike
              8 = Other

**Comment by ckrey** [comment]
English: Mountain Bike
Deutsch: Mountainbike

<img width="804" alt="Bildschirmfoto 2019-10-11 um 13 34 50" src="https://user-images.githubusercontent.com/4027289/66648484-f1716480-ec2b-11e9-8ba1-513aa174505c.png">

**Comment by ckrey** [comment]
![IMG_3E2AD96E303B-1](https://user-images.githubusercontent.com/4027289/66648543-0cdc6f80-ec2c-11e9-9c38-73e69f7f2c25.jpg)
