### ISSUE TITLE
additional statistics: average idle time, average distance

### ISSUE THREAD

**Issue by selphiron** [simra-project/simra-ios#28]
average idle time (Durchschnittliche Stillstanddauer): idle time / number of rides (in minutes)
average distance (Durchschnittliche Distanz): total distance / number of rides (in km/h or mph)

**Comment by ckrey** [comment]
<img width="375" alt="Screenshot 2020-01-21 at 13 12 57" src="https://user-images.githubusercontent.com/4027289/72804632-1759cc80-3c51-11ea-83fb-ff85748afed7.png">
