### ISSUE TITLE
Fehlende URLs

### ISSUE THREAD

**Issue by ckrey** [simra-project/simra-ios#3]
Es fehlen noch die folgenden URLs zum verlinken aus der iOS App:

- Impressum deutsch
- Impressum english

- Anleitung iOS App deutsch
- Anleitung iOS App english

Müssen wir wegen der Nutzung von Apple Maps auf iOS auf eine **andere** Datenschutzerklärung als bei Android verlinken oder wird diese generalisiert geschrieben?

**Comment by selphiron** [comment]
Impressum deutsch: https://www.tu-berlin.de/servicemenue/impressum/parameter/mobil/
Impressum englisch: https://www.tu-berlin.de/servicemenue/impressum/parameter/en/mobil/

**Comment by ckrey** [comment]
Beim ersten App-Start auf eine PDF verlinken, die die App erklärt (mit Screenshots). Das PDF wird von uns erstellt.
- `http://www.mcc.tu-berlin.de/fileadmin/fg344/simra/SimRa_Instructions_IOS.pdf`
- `http://www.mcc.tu-berlin.de/fileadmin/fg344/simra/SimRa_Anleitung_IOS.pdf`

diese Links enthalten derzeit noch die Android-Anleitungen, werden jedoch bald auf die IOS-Anleitungen verweisen.
