### ISSUE TITLE
Number of uploaded rides too high

### ISSUE THREAD

**Issue by selphiron** [simra-project/simra-ios#31]
> @SimRa_Berlin
 Ich habe heute meine allererste Fahrr hochgeladen und soll laut Statistik bereits 12 gefahren sein?! 
🤔

https://twitter.com/Uckerhonig_de/status/1229768305386442754/photo/1

The server was down while this user tried to upload his rides. Can this be the cause?

**Comment by ckrey** [comment]
Ja leider wahr: Die Statistik wird bei jedem Versuch hochzuladen upgedated.

**Comment by ckrey** [comment]
Das bedeutet aber auch, dass der Stand der Fahrt beim ersten Hochladeversuch gezählt wird. Da noch nicht tatsächlich hochgeladen wurde, ist danach noch weitere Bearbeitung möglich
