### ISSUE TITLE
Neues REST API

### ISSUE THREAD

**Issue by ckrey** [simra-project/simra-ios#4]

**Comment by ckrey** [comment]
Die neuen REST-Anfragen sind bereit.
Um eine Fahrt + Annotationen zum ersten Mal hochzuladen:
POST: https://vm1.mcc.tu-berlin.de:8082/10/ride?loc=other&clientHash=e8d9dc54

Um die demographischen Daten zum ersten Mal hochzuladen:
POST:
https://vm1.mcc.tu-berlin.de:8082/10/profile?loc=other&clientHash=e8d9dc54

Um Absturzmeldungen hochzuladen:
POST:
https://vm1.mcc.tu-berlin.de:8082/10/crash?loc=other&clientHash=e8d9dc54

Wäre gut, wenn die Absturzmeldungen in der zweiten Zeile einen Timestamp haben von wann die Meldung ist (nach einem Doppelpunkt und einem Leerzeichen):
System Timestamp: 1553587411974

Sonst wird einfach Serverseitig der aktuelle Timestamp genommen.

Um eine Fahrt + Annotationen zu aktualisieren (wobei wir gesagt haben, dass wir das doch nicht machen wollen):
PUT: 
https://vm1.mcc.tu-berlin.de:8082/10/update?fileHash=VM2_983038515&filePassword=bdCPO02fjZ&loc=de&clientHash=ddcb03f0

Um die demographischen Daten zu aktualisieren:
PUT:
https://vm1.mcc.tu-berlin.de:8082/10/profile?fileHash=VM2_634425817&filePassword=rzCVkr7EYA&loc=other&clientHash=e8d9dc54

**Comment by selphiron** [comment]
Korrektur für die Aktualisierung von Fahrt + Annotationen:
PUT:
https://vm1.mcc.tu-berlin.de:8082/10/ride?fileHash=VM2_983038515&filePassword=bdCPO02fjZ&loc=de&clientHash=ddcb03f0
