### ISSUE TITLE
Unterschiedliche Automatische Erkennung

### ISSUE THREAD

**Issue by ckrey** [simra-project/simra-ios#5]
Android in der Hosentasche, iOS am Lenker // Daten 07.04.2019, 16:36 
Sind die errechneten Punkte nachvollziebar?

![a318c754-8975-441b-9470-8974891e46b5](https://user-images.githubusercontent.com/4027289/55689291-015d7280-5983-11e9-921e-3ba54e6ac857.jpg)

![IMG_7894](https://user-images.githubusercontent.com/4027289/55689277-d6731e80-5982-11e9-8b82-1e72512f4c22.png)

**Comment by selphiron** [comment]
Nein, ich sehe es zum ersten Mal, dass die Ereignisse außerhalb der Route liegen und es ist mir ein Rätsel, wie das passieren kann. Bewegen sich die Marker, wenn du ranzoomst? Welches System läuft da? (Gerät + Android-Version) und welche App-Version hast du? Die aus dem Play Store?

**Comment by ckrey** [comment]
App aus Play Store Version 20. Android 9, Samsung S8. Ja, die Marker bewegen sich beim Zoomen, kommen aber nie auf die Route

**Comment by selphiron** [comment]
Okay und wenn du ranzoomst, zeigen die unteren Spitzen immer auf die exakt gleiche Position oder bewegen sie sich? Ich habe die Vermutung, dass es ein Skalierungsproblem ist. Die Marker müssten nämlich größer sein. Kann es sein, dass die Bilder nicht den für sie reservierten Platz ausfüllen, sondern in der linken oberen Ecke in klein erscheinen? Weil wenn man die Icons nach rechts unten streckt, ist der Routenverlauf ja doch zu erkennen.

**Comment by ckrey** [comment]
Das Handy war von einem Freund, ich kann also im Moment nicht nachschauen. Aber ja, die Spitzen haben sich bewegt. 

Der Routenverlauf ist ja anhand der roten Linie zu erkenne, aber die Zuordnung der Incidents fällt schwer

**Comment by selphiron** [comment]
Was ich auch mal bitten würde bei Gelegenheit zu überprüfen: Ereignisse selber hinzufügen (mit dem Button an der oberen rechten Ecke). Sind die dann ebenfalls so verschoben oder auf der Route drauf? Und sind die dann größer?

**Comment by selphiron** [comment]
Ok, habe das Problem glaube ich gefunden. Meine Vermutung, dass die Bilder falsch bzw. nicht skaliert werden scheint richtig gewesen zu sein.
