### ISSUE TITLE
GPX, GeoJson and KML Export of SimRa rides

### ISSUE THREAD

**Issue by selphiron** [simra-project/simra-ios#56]
Since there are a lot of apps that a user may want to track their bike rides with, it would increase the functionality of SimRa, if it would be possible to export the rides to the GPX, GDB and KML formats.

This should function like the existing export by long tapping the ride.

**Comment by ckrey** [comment]
- why not `GeoJSON` ?
- why support proprietary format `GDB`?  Where is the spec?
- for all formats: which fields should be mapped? Minimal `lat,lon`?

**Comment by selphiron** [comment]
Yes, we can add GeoJSON instead of GDB.
lat, lon and timestamp, if it is supported for the resprective format.

**Comment by ckrey** [comment]
- GeoJSON
-- overview: https://de.wikipedia.org/wiki/GeoJSON 
-- spec: https://datatracker.ietf.org/doc/html/rfc7946
-- test: https://geojson.io, https://geojsonlint.com
-- output is a minimal `trip.geojson` consiting of a `LineString` object:
```
{"type":"LineString","coordinates":[
[6.688227,51.195765]
...
,[6.688217,51.195764]
]}
```

**Comment by ckrey** [comment]
- GPX
-- overview: https://de.wikipedia.org/wiki/GPS_Exchange_Format
-- spec: https://www.topografix.com/gpx.asp
-- test: https://www.j-berkemeier.de/ShowGPX.html
-- output is a minimal `trip.gpx` consisting of a track object:
```
<?xml version="1.0" enconding="UTF-8" standalone="no" ?>
<gpx version="1.1" creator="SimRa iOS"><trk><trkseg>
<trkpt lat="51.195846" lon="6.688384"></trkpt>
...
<trkpt lat="51.195841" lon="6.688317"></trkpt>
</trkseg></trk></gpx>
```

**Comment by ckrey** [comment]
- KML
-- overview: https://de.wikipedia.org/wiki/Keyhole_Markup_Language
-- spec: https://developers.google.com/kml/documentation/kmlreference?csw=1
-- test: https://earth.google.com/ (Projects/New Project/Import KML) 
-- output is a minimal `trip.kml`consisting of a track object:
```
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<kml xmlns="http://www.opengis.net/kml/2.2"><Document><Placemark id="Simra"><LineString id="Simra"><coordinates>
6.688384,51.195846
...
6.688317,51.195841
</coordinates></LineString></Placemark></Document></kml>
```
