### ISSUE TITLE
Show only "real" closs pass incidents generated by OpenBikeSensor

### ISSUE THREAD

**Issue by selphiron** [simra-project/simra-ios#63]
The OpenBikeSensor can be coupled with SimRa via Bluetooth. It has distance sensors to the left and right and a hardware button that can be attached to the bicycle handle bar.
When the cyclist is bein overtaken by a car, (s)he presses the button and SimRa adds a marker to the location where the cylist was, when the button was pressed. The marker placed at the location has "Close Pass Incident" preselected as the near miss incident and the text description field contains the measured distance by the OpenBikeSensor.
Right now, every time the button is pressed, such a marker is placed.
However, overtakings with a distance of >1,50m are not a close pass incident and thus should not be displayed on the map in SimRa.
@iHamzaaK has already created a Pull Request for that (#62) can you review that please @ckrey ?

**Comment by ckrey** [comment]
I did and requested changes

**Comment by ckrey** [comment]
@selphiron As @iHamzaaK did not react, I un-did the format changes and fixed the typo. Unfortunately I cannot test with OBS here

**Comment by selphiron** [comment]
Perfect, Thank you! I am going to test it with the next version (TestFlight)
