### ISSUE TITLE
show news only once

### ISSUE THREAD

**Issue by foss-** [simra-project/simra-ios#65]
iOS: 15.4
SimRa: 1.8

**Currently**
News is shown on every launch.

**Expected**
Show news only once. After that there should be no news overlay until another news is published. Otherwise this quickly becomes a nuisance to users and slows down their workflow.

**Comment by ckrey** [comment]
@foss sorry, we cannot reproduce the problem here. 
- would you attach a screen shot?
- which language do you use on your iPhone?

**Comment by foss-** [comment]
iOS is set to English. Wanted to reproduce and problem is gone. Restarted phone and while the news are still not shown, I was (again) asked to pick a region, which was done already earlier. Not sure about both behaviors.

Closing this bug as I am no longer able to reproduce. Will re-open should the problem return.
