### ISSUE TITLE
Crash bei längeren Strecken

### ISSUE THREAD

**Issue by ckrey** [simra-project/simra-ios#67]
ich hatte es am Anfang schon einmal gemeldet, aber irgendwie scheint nichts passiert zu sein.

Bei kurzen Strecken (<15km) funktioniert der Upload ohne Probleme. Bei längeren Strecken über 30km scheint die Datenaufbereitung zu starten und nach etwa 20 Sekunden schließt sich die App, bzw geht in den Hintergrund Ein Upload findet nicht statt.
Das ist unabhängig vom benutzten WLAN oder 4G.
iPhone XR, 12GB frei, IOS 15.5

Ist der Bug auf dem Schirm und wann ändert sich was? So macht das für mich keinen Sinn. Die App ist im aktuellen Stand pure Stromverschwendung.
Ich warte jetzt noch 14 Tage, danach lösche ich die App.

**Comment by ckrey** [comment]
Die Datensammlung erfolgt im Speicher und wird bei Beendigung in CSV umgewandelt. Bei sehr langen Strecken (> 30km!) kann es dort zu Speicherproblemen kommen (im Hauptspeicher, nicht auf der “Platte” (Flash)).
Zu der Zeit wird auch gar kein Upload gemacht, es ist reine interne Bearbeitung.

Ist nicht zu ändern ohne die gesamte Verarbeitung/Speicherung zu überarbeiten.

**Comment by ckrey** [comment]
Es gibt mehrere Dinge zu beachten:

- wegen #39 müssen die Aufzeichnungen von Position und Beschleunigungssensor getrennt aufgezeichnet und später gemischt werden um die unterschiedlichen Zeitstempel in die richtige Reihenfolge zu bringen
- Momentan werden Streckenlänge und -dauer jeweils ad-hoc aus den im Speicher gehaltenen Positionen berechnet. Das muss angepasst werden (wenigstens Lat/Lon/Zeitstempel)
- Um die Strecke zum Editieren auf der Karte anzeigen zu können müssen wenigstens Lat/Lon/Reihenfolge
- Die Konvertierung in GPX, KML und GeoJSON erfolgt ebenfalls aus den im Speicher gehaltenen Positionen (Lat/Lon/Reihenfolge)

**Comment by selphiron** [comment]
That depends on the internet connection and the length of the ride (= size of the file). I used the sample file on my PC (fast LAN connection) and it took 1 second. On my smartphone (wifi) it took longer. Maybe, we could make the timeout ride-length-dependant? 5 seconds for every of the file size? So 4 MB would be 20 seconds. What do you think @ckrey ?
