### ISSUE TITLE
Region sorting options hard to find

### ISSUE THREAD

**Issue by foss-** [simra-project/simra-ios#70]
E.g. users living in `Wiesbaden` will have a hard time finding their region if they search Wiesbaden in the alphabetical list, since that town is hidden / listed together with `Mainz/Wiesbaden`.

Users don't care how regions are structure so I would argue to instead of listing multiple cities as single entry, to instead list the city names individually for improved discoverability. The individual listings can still be connected to a collective region of course.

**Comment by selphiron** [comment]
I agree, but we have a feature that can show the three nearest regions based on GPS. Doesn't that solve the problem?

**Comment by foss-** [comment]
Good point. Feel free to close this. Feature seems to work on android, no iOS device around currently to verify.
