### ISSUE TITLE
Trouble applying incident details

### ISSUE THREAD

**Issue by foss-** [simra-project/simra-ios#71]
SimRa-25
iOS 16.0

1. Record Trip
2. Select Trip
3. Tap Pin on Map
4. Select Incident and fill details

**Currently**

Tapping `Done` in bottom right does nothing.

**Expected**

`Done` should close Incident Details and go back to map overview.

It would be more intuitive to *always* store changes made by user, remove `Done` button. As soon as user taps `Edit Trip` to navigate back to map, changes are stored. Wouldn't that simplify the UI and resolve the current issue that `Done` is not functional?

**Comment by ckrey** [comment]
The "Done" button is functional. It finishes the keyboard entry for the multiline comment text field.
When you select the comment field, the keyboard appears, when you press "Done", the keyboard disappears.

The changes are always stored.

**Comment by foss-** [comment]
For me, the done button was also shown when the comment field was not selected. As per your description, wouldn't it make sense to only show when the comment field is actively selected and keyboard is shown? For me, Done was always shown, even without the comment field selected.

**Comment by ckrey** [comment]
You are right, the button is currently always enabled. Will disabled when not editing the comment field in the next version
